"""add ai search tables

Revision ID: 2380fd846285
Revises: ADD_COMPOSITE_INDEXES
Create Date: 2026-01-07 15:42:50.549467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2380fd846285'
down_revision: Union[str, Sequence[str], None] = 'ADD_COMPOSITE_INDEXES'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curated_closet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hero_image_url', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_closet_created_at'), 'curated_closet', ['created_at'], unique=False)
    op.create_index(op.f('ix_curated_closet_user_id'), 'curated_closet', ['user_id'], unique=False)
    op.create_table('closet_reco_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('closet_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['closet_id'], ['closet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_closet_reco_cache_closet_id'), 'closet_reco_cache', ['closet_id'], unique=False)
    op.create_index(op.f('ix_closet_reco_cache_generated_at'), 'closet_reco_cache', ['generated_at'], unique=False)
    op.create_table('curated_closet_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curated_closet_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['curated_closet_id'], ['curated_closet.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_curated_closet_item_curated_closet_id'), 'curated_closet_item', ['curated_closet_id'], unique=False)
    op.create_index(op.f('ix_curated_closet_item_product_id'), 'curated_closet_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_curated_closet_item_rank'), 'curated_closet_item', ['rank'], unique=False)
    op.create_index(op.f('ix_curated_closet_item_variant_id'), 'curated_closet_item', ['variant_id'], unique=False)
    op.create_table('variant_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('vector_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_embedding_created_at'), 'variant_embedding', ['created_at'], unique=False)
    op.create_index(op.f('ix_variant_embedding_model_name'), 'variant_embedding', ['model_name'], unique=False)
    op.create_index(op.f('ix_variant_embedding_variant_id'), 'variant_embedding', ['variant_id'], unique=True)
    op.create_table('image_embedding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=True),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('vector_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_embedding_created_at'), 'image_embedding', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_embedding_image_id'), 'image_embedding', ['image_id'], unique=True)
    op.create_index(op.f('ix_image_embedding_model_name'), 'image_embedding', ['model_name'], unique=False)
    op.create_table('search_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_image_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['query_image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_session_created_at'), 'search_session', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_session_query_image_id'), 'search_session', ['query_image_id'], unique=False)
    op.create_index(op.f('ix_search_session_user_id'), 'search_session', ['user_id'], unique=False)
    op.create_table('search_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['search_session.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_event_created_at'), 'search_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_event_event_type'), 'search_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_search_event_product_id'), 'search_event', ['product_id'], unique=False)
    op.create_index(op.f('ix_search_event_session_id'), 'search_event', ['session_id'], unique=False)
    op.create_index(op.f('ix_search_event_variant_id'), 'search_event', ['variant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_event_variant_id'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_session_id'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_product_id'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_event_type'), table_name='search_event')
    op.drop_index(op.f('ix_search_event_created_at'), table_name='search_event')
    op.drop_table('search_event')
    op.drop_index(op.f('ix_search_session_user_id'), table_name='search_session')
    op.drop_index(op.f('ix_search_session_query_image_id'), table_name='search_session')
    op.drop_index(op.f('ix_search_session_created_at'), table_name='search_session')
    op.drop_table('search_session')
    op.drop_index(op.f('ix_image_embedding_model_name'), table_name='image_embedding')
    op.drop_index(op.f('ix_image_embedding_image_id'), table_name='image_embedding')
    op.drop_index(op.f('ix_image_embedding_created_at'), table_name='image_embedding')
    op.drop_table('image_embedding')
    op.drop_index(op.f('ix_variant_embedding_variant_id'), table_name='variant_embedding')
    op.drop_index(op.f('ix_variant_embedding_model_name'), table_name='variant_embedding')
    op.drop_index(op.f('ix_variant_embedding_created_at'), table_name='variant_embedding')
    op.drop_table('variant_embedding')
    op.drop_index(op.f('ix_curated_closet_item_variant_id'), table_name='curated_closet_item')
    op.drop_index(op.f('ix_curated_closet_item_rank'), table_name='curated_closet_item')
    op.drop_index(op.f('ix_curated_closet_item_product_id'), table_name='curated_closet_item')
    op.drop_index(op.f('ix_curated_closet_item_curated_closet_id'), table_name='curated_closet_item')
    op.drop_table('curated_closet_item')
    op.drop_index(op.f('ix_closet_reco_cache_generated_at'), table_name='closet_reco_cache')
    op.drop_index(op.f('ix_closet_reco_cache_closet_id'), table_name='closet_reco_cache')
    op.drop_table('closet_reco_cache')
    op.drop_index(op.f('ix_curated_closet_user_id'), table_name='curated_closet')
    op.drop_index(op.f('ix_curated_closet_created_at'), table_name='curated_closet')
    op.drop_table('curated_closet')
    # ### end Alembic commands ###
